name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Test Docker Compose
      run: |
        docker compose up --build -d

        export PASS=0
        export TEST_VAL="<h1>CS 495 Website</h1>"
        
        export VAL=$(curl -k https://localhost/)
        
        if [[ "$VAL" = "$TEST_VAL" ]]; then
          echo "Assertion passed"
        else
          echo "Assertion failed"
          echo "val: "
          echo "$VAL"
          PASS=1
        fi

        docker compose down
        exit $PASS

# this is a dumb CI test, but this is boilerplate code and 
# I don't like github actions for CI/CD so it's whatever for now