name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Test Docker Compose
      run: |
        docker compose up --build -d
        sleep 10
        # ^^ probably an excessively cautious startup time

        export PASS=0
        export TEST_VAL=<h1>CS 495 Website</h1>
        
        export VAL=$(curl localhost:443)
        
        if [[ "$VAL" = "$TEST_VAL" ]]; then
          echo "Assertion passed"
        else
          echo "Assertion failed"
          echo "val: "
          echo "$VAL"
          PASS=1
        fi

        docker compose down
        exit $PASS
        
